[tool.poetry]
name = "beautysh"
version = "6.1.0"
description = "A Bash beautifier for the masses."
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/lovesegfault/beautysh"
repository = "https://github.com/lovesegfault/beautysh"
keywords = ["beautify", "bash", "shell", "beautifier", "script", "auto"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Text Processing :: Filters",
    "Topic :: Utilities"
]
include = ["LICENSE"]


[tool.poetry.scripts]
beautysh = "beautysh:main"

[tool.poetry.dependencies]
python = "^3.6.2"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^21.5b2"
isort = "^5.8.0"
flakehell = "^0.9.0"
pre-commit = "^2.13.0"
python-language-server = "^0.36.2"
mypy = "^0.901"
types-colorama = "^0.4.0"

[tool.pytest.ini_options]
addopts = "-v -Wdefault"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99

[tool.flakehell]
exclude = ["build"]
max_line_length = 99
# c.f. https://github.com/flakehell/flakehell/issues/10
extended_default_ignore=[ ]

[tool.flakehell.plugins]
mccabe = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
